export const tableDataHeader = [
  'Оплачен',
  'Клиент',
  'Услуга',
  'Скидка клиенту',
  'Сумма счета, руб',
  'Процент партнера',
  'Вознаграждение, руб',
  'Акцепт',
];

export let tableData = [
  {
    date_pay: '2024-06-10',
    client: 'a****************@hoster.by',
    info: 'Хостинг - Битрикс-хостинг - Битрикс № 2 NVMe',
    skidka: '3.00%',
    sum: '4094.37',
    partner_percent: '5%',
    partner_sum: '24.00',
    accept: 1,
  },
  {
    date_pay: '2024-06-10',
    client: 'm******************@hoster.by',
    info: 'hoster Guard - Basic - Basic',
    skidka: '0.00%',
    sum: '111.00',
    partner_percent: '1%',
    partner_sum: '15.00',
    accept: 1,
  },
  {
    date_pay: '2024-05-24',
    client: 'm******************@hoster.by',
    info: 'hoster Guard - Basic - Enterprice',
    skidka: '0.00%',
    sum: '222.00',
    partner_percent: '1%',
    partner_sum: '12.00',
    accept: 0,
  },
  {
    date_pay: '2024-05-24',
    client: 'm******************@hoster.by',
    info: 'hoster Guard - Basic - Pro',
    skidka: '0.00%',
    sum: '333.00',
    partner_percent: '1%',
    partner_sum: '25.00',
    accept: 0,
  },
  {
    date_pay: '2024-05-23',
    client: 'i***********@hoster.by',
    info: 'Хостинг - Unix-хостинг - Профи - Минск',
    skidka: '0.00%',
    sum: '22.00',
    partner_percent: '1%',
    partner_sum: '22.00',
    accept: 1,
  },
  {
    date_pay: '2024-05-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '22.00',
    accept: 1,
  },
  {
    date_pay: '2024-05-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '23.00',
    accept: 1,
  },
  {
    date_pay: '2024-05-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '0.36',
    accept: 1,
  },
  {
    date_pay: '2024-04-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '159.00',
    accept: 1,
  },
  {
    date_pay: '2024-03-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '123.00',
    accept: 1,
  },
  {
    date_pay: '2024-02-23',
    client: 'v***************@hoster.by',
    info: 'Домены - BY',
    skidka: '0.00%',
    sum: '1160.00',
    partner_percent: '1%',
    partner_sum: '236.00',
    accept: 1,
  },
  {
    date_pay: '2024-02-23',
    client: 'c**********@hoster.by',
    info: 'Хостинг - Windows-хостинг - Профи',
    skidka: '0.00%',
    sum: '75.00',
    partner_percent: '1%',
    partner_sum: '75.00',
    accept: 1,
  },
  {
    date_pay: '2024-01-20',
    client: 'e**************@hoster.by',
    info: 'Хостинг - Unix-хостинг - Лайт',
    skidka: '0.00%',
    sum: '1.00',
    partner_percent: '15%',
    partner_sum: '0.15',
    accept: 1,
  },
];
